### ISSUE TITLE
Return actions

### ISSUE THREAD

**Issue by jjvanzon** [jjvanzon/JJ.Framework#75]
A return action may for instance be when being redirected to a login page and after logging in being redirected back to the page you came from. Several ideas were tried to give return actions a place in the architecture. The `JJ.Demos.ReturnActions` projects explore several of these ideas, some of which went out of favor. The initial idea was to try and implement a platform-agnostic variation of return URL's. That became an arguably convoluted solution where return URL's were modeled as a graph of action information. Eventually, a simpler solution was put in favor: at most return URL's might be stored as strings in view model objects as a 'platform-independent' representation of return actions.

- [x] Related: #74

These are the notes and brainstorms around this.

### 2015-02-19 Brainstorm Return Actions

- [x] Not all return actions in MVC might be usable, because MVC might not allow a separate action for opening Edit from List and opening Edit from Details with post data unless you make a different URL. You can use return URL’s in MVC to get the same effect.
- [x] It might be cool to have a helper that converts my action descriptor to an action url, so I can pass along a return address to as a parameter to the Edit GET action, so I can still use the ReturnAction from my navigation model for it. 
- [x] Double return actions seem a little trickier in the navigation model.
- [x] Returning to the screen you came from seems quite a bit to manage. Maybe a framework solution might be good. Maybe some sort of PresenterBase in JJ.Framework.Presentation. > It turned out to work ok with a Helper instead.
- [x] If action URLs can be translated to an action descriptor, action info might be passed from controllers to use the presenter actions, so those overloads might be used. That may open the door to integrating stacked up MVC return url’s with stacked action descriptors.
- [x] Maybe rename it to ActionInfo, to prevent conflict with an MVC class name. Doing the same rename trick might not work for replacing ParameterDescriptor (conflicting with MVC) with ParameterInfo, because it may conflict with Reflection. So then it might be renamed to ActionParameterInfo. It may create simpler names when calling it ActionInfo instead of ActionDescriptor and then it may be less likely to confuse it with the MVC class.
- [x] The Helper construct might be used, maybe an ActionInfoHelper that might translate an ActionInfo to a delegate or execute a call, which syntactically seems the inverse of what ActionInfoHelper may already do: translating an expression to an ActionInfo. That may create a place to put much of the ActionDispatcher code, but then in the framework, and may make is possible to program improvements to that code in one place. Framework.Mvc might become able to translate ActionInfo to and from URL’s, so return addresses may be included in an URL, when desired. That may translate the way the Presenter layer might handle return actions to the way web may handle return URL’s. Furthermore, there may be a need for *paths* of action info’s. A recursive ActionInfo.ReturnAction property may be used for that. In Framework.Mvc it might be nice to translate those to URL’s but it would seem logical that the return URL’s may be cascadingly encoded to the next URL’s return parameter, so there might be multiple levels of URL encoding. This may also allow transferring return action info through post data if desired.
- [x] Somehow this might not be enough to just use multi-level return actions on any level desired.
Perhaps at every point where a return action might be used, potentially a multi-level return action might be desired. But next to primitive parameters a dynamically dispatched action might also support a chain of return actions. That might be built into the ActionInfo and delegating conversion to the ActionInfoHelper. ActionHelper might be a better name, perhaps.
Action parameters might not be view models themselves. Things might not go as far as that. So parsing action parameters as view models might be a step to far, but perhaps occasionally more than just primitive parameters to dispatch to an action are desired. Dynamically dispatching post actions might not be a desired requirement yet.
- [x] Multi-level return actions require action dispatching that can handle that return action info.
It is the equivalent of URL parameters being values and sometimes whole URL’s.
- [x] MasterController: it looks like the code could be generalized to framework code.
- [x] return action info with authenticated user name in it seems a security problem.
- [x] I think I somehow want to keep the current experiment putting return action in the post data as a demo project.

### 2015-02-26 Brainstorm Action Dispatching

I am not satisfied with action dispatching requiring so much very specific application code:
GetActionResult and ActionDispatcher in MVC should be replaced by a generic solution, even if this means sacrificing compile-time type-checking.

If you want the platform independent ActionDispatcher to take a presenter type instead of a presenter instance, you would need to pass the constructor arguments to it, perhaps as an object, perhaps as an anonymous type, just like in MVC and in the SqlExecutor API. But you may want to be forgiving when it comes to either supplying or not supplying constructor arguments, so you can pass the union of constructor arguments to the ActionDispatcher and always get your result. ~~However: how do you know which constructor overload to pick? Should you somehow dynamically pick the best match?~~ Should you insist there is only one constructor? The last one is the easiest to program. ~~Should you be forgiving about the types of the constructor arguments? I think not.~~ These ActionDispatchers might not be very flexible at first and only work when there are no overloads, but the fact that you have a central ActionDispatcher that can do the work for you without having to program other helpers around it with specific technical requirements (otherwise it would not work) might be a good thing to have, even when it has limitations (that may later be improved).

The key, I might think, is providing arguments dynamically without any compile-time type-checking typically by means of anonymous types.

I think I can very well live with an ActionDispatcher with limitations, if this does mean one call will do the job. The limitations can be gotten rid of later.

Steps:
- Refactor code in MyActionDispatcher to a general ActionDispatcher
- Refactor code in MasterController to a MyMvcActionDispatcer
- Refactor MasterController / MyMvcActionDispatcher to not repeat so much logic.
- Refactor MyMvcActionDispatcher to a general MvcActionDispatcher.
 
#### TODO Presenter ActionDispatcher

- There are two problems: the constructor arguments
- And converting presenter name to presenter type name.

The constructor arguments I feel I can find a solution for easily.
Converting the presenter name to a presenter type name could be a one-off relatively slow operation that can be cached after which it might not be slow anymore, that unfortunately maylead to ambiguity.
~~It may be a choice to insist on registration of the assemblies of which you want to use presenters, which may require additional non-obvious application code, that might however be pointed out with an exception message.~~
Another option may be simply searching for a presenter with that type name in the app domain (which may lead to ambiguity in a less conventional situation). One could say such problems might be there in MVC itself too and then forgive oneself ‘because Microsoft does it too’, but that might not always be a good argument. Just because Microsoft did it, might not mean that there isn't a better way.

I think I choose failure in case of ambiguous presenter names over insisting a programmer do additional non-obvious work. Because that solution would work under ‘normal circumstances’ (i.e. circumstances that would always work if you follow certain architectural rules), and it satisfies the goal of having action dispatching with a single method call (one call does it all), in place of quite some bloat of plumbing code. Also, if you do not work within certain architectural rules, there is a fallback, to perhaps programming a dispatch helper on top of the ActionDispatcher that may avoid ambiguous presenter names.

~~Again: yes, a lot might be done to permit exceptional cases, so that a programmer might not run into a roadblock e.g. when using overloads, but that might be solved in the future and meanwhile may allow a one-call dynamic action dispatching.~~

#### TODO MvcActionDispatcher

- Generalized code for delegating to RedirectToAction or to View().
- Injecting conversion from view model to action parameters.
- Doing something with ValidationMessages. 
- Doing something with the split up between edit and create actions.
- Calling protected members of the Controller class using reflection.

There might be quite some delegates in this solution.
getActionParametersDelegate
getValidationMessagesDelegate
predicate

predicate might be x => x.IsNew

~~ActionDispatcher might not be a proper term, because you might not always dispatch to an action. Sometimes dispatchins to a view that might not have its own controller action.~~

The mappings might not have a unique key. There might be multiple mappings for the same view model. But without a hashing collection type it might have less reliable performance, and the good hashing collections have a unique key. You might let the value be an array.

Architecture / pattern: using TryGetValue, because it might be faster than ContainsKey and an indexer call.

I wonder if I should have made it ICollection<KeyValuePair<T, U>>. No IList.

Also might port the Accessor tests to the new code base.
Perhaps also mention in the old code base that the code was fully ported.

Prettier member names in MVC ActionDispatcher.

- Debugging through the MVC DispatchAction some more.

TempDataKey is now in the framework...
TODO: Refactoring accessor tests.
- Formatting the field names and not use public fields.
- Making some classes internal.
- The methods like IntMethodIntInt may not have been tested yet.
The ControllerAccessor’s delegating to the Accessor class might not be the fastest solution.

### 2015-03-02 Done Return URLs

- [x] Might UrlHelpers.GetReturnUrl not automatically encode the deeper return action too?
- [x] I might not need the overloads that take a collection.
- [x] Maybe the ‘Try’ verb should be the only option in the UrlHelpers.
- [x] Checkig returnUrlParameterName is for null or white space.
- [x] It may be strange that EditPresenter.Save does not have tolerance for no return action, just because Show set it... what if return actions are not supported by the presentation technology in any possible way? Return actions might better be optional and fall back to a default.
- [x] Do you get less prettu URLs and duplicate URLs if you use return URLs? Does google like that? > There are solutions e.g. canonical URL’s and read-only content might not have return URL’s.
- [x] CancelEdit might be removed.
- [x] ~~Also put the view models for the return action information in framework code.
Perhaps in JJ.Framework.Presentation.Mvc.Razor with the same content copying trick as JJ.Framework.Presentation.JavaScript. > They probably can be deleted after action URL’s are realized.~~
- [x] ~~// Code-smell: repeated code. Similar to the other overload.~~
- [x] ~~GetReturnUrl_ByList: // TODO: Performance of these string operations is not great.~~
- [x] Trivial:
    - [x] The UrlParser might show the full URL in exception messages.
    - [x] UrlParser may need more testing.
    - [x] Put DebuggerDisplay of UrlInfo in an UrlBuilder class?
    - [x] I only encode parameter values, which may not be the only thing to encode.
    - [x] Delegating UrlBuilding to the UrlBuilder class.
    - [x] Still might have GetReturnUrl + variations to go.
    - [x] Handling normal parameter: throwing an exception if the parameter is not found. Doing that in other places too when matching. Next to the not found parameter, perhaps even mention the possible parameters.
    - [x] Might first program reflection tricks inside the ActionDispatcher itself, but they may be to be moved to JJ.Framework.Reflection after they are done.
        - [x] ~~ActionDispatcher (Presentation): Cache constructor parameters too.~~
        - [x] ~~Does .NET reflection have the means to query for a constructor without regarding type? If you have picked the best matching constructor by ‘brute’ sequential processing, could it be cached it by any means? (In other words: is there an appropriate cache key?)~~
- [x] ActionDispatching restructuring:
    - [x] Perhaps it may be clearer to call ActionDispatcher rather than having to call UrlHelpers.
    - [x] The URLs now have presenter action info in them, not MVC action info.
    - [x] To solve this more extensive dispatch mapping might be applied with a class for each mapping, perhaps imposing a little performance penalty for each URL-encoded return action.
    - [x] And more code might be moved to the ActionDispatcher, which may not be a bad thing.
    - [x] ~~Also the URL parameters might be mapped. Like this?~~
        - [x] ~~AddParameterMapping("lang", "cultureName");~~
        - [x] ~~AddParameterMapping("ret", null);~~
    - [x] ~~Presenter a generic type argument? No, it might not have a presenter. Then a property of type Type?
    - [x] ~~//PresenterType = typeof(QuestionDetailsPresenter);~~
    - [x] This might be a nice syntax:
    - [x] SetPresenterAction(PresenterNames.QuestionListPresenter, PresenterActionNames.Show);
    - [x] SetControllerAction(ControllerNames.Questions, ActionNames.Index);
    - [x] > Perhaps not, because there might be a controller and no action.
    - [x] > There may be a few nice overloads for syntactic sugar now. Even though it may be less strict at compile type, it does seem to make the code for view mapping more readable and overviewable.
    - [x] WAS AT: just done with letting the ActionDispatcher retrieve ViewMapping implementations and using those to dispatch, making the original Map method obsolete.
I might now program making a return URL an MVC URL rather than the names in the presenter. This does require mapping of parameter names too.
    - [x] Maybe some protected Map methods in the ViewMapping base class would offer some syntactic sugar if it only concerns names.
    - [x] Maybe more syntactic sugar may be desired, to map a view name too in MapController and leave out the constructor argument and check it in the dispatch method? It may not be as strict in the definition, but it may read better. There might be overloads in which you leave out the least likely string from the parameter list. It should be easy too.
    - [x] ~~Not all parameters seem to be mapped yet.~~
    - [x] ~~May put more specific information about what to do in this exception:~~
        - [x] ~~"Parameter '{0}' for method '{1}' of type '{2}' not found in ActionInfo. Permitted parameters: {3}. ActionInfo parameters: {4}." Also: when one of the parameter lists is empty the exception message may not be clear yet.~~
    - [x] Also checking that view is not null or empty during the dispatching.
    - [x] ~~Making the action names more strongly typed by using expressions may produce more complicated code.~~
    - [x] Regular URL helpers might be used for generating a return URL in the view code. > Working on it.
    - [x] This URL did not work: /Questions/Index/100
    - [x] ~~So a special variation on Url.Action might be desired, that generates an URL that a dispatcher may handle.~~ Or something that can interpret the 3rd part of the path as the first parameter of the controller? ~~Oh, no, that might not be doable. The mapping of MVC to action method parameters may be too dynamic for that.~~
    -[x] > Unnamed MVC parameters might now be mapped to presenter parameters in the order in which MapParameter may be called in the ViewMapping.
    -[x] The Presenter-level ActionDispatcher seems to expects a parameter value for optional Presenter action method parameters, so you might want to revert to the default. It happens for this URL: “/Questions/Index”. The Dispatcher seems to expect a value for the pageIndex parameter of the presenter, even though that parameter may be optional.
    -[x] The ActionDispatcher.AddMapping* might could be replaced by .ToNonUniqueDictionary().
    -[x] The ActionDispatcher summaries might be checked and improved.
-----
- [x] Some of the following implementations may have been applied to an app called QuestionAndAnswer.
- [x] App code:
    - [x] ~~Giving ConfirmDelete a ret.~~
    - [x] ~~In case of Create on Details via Login, the multiple ret levels do not seem to be included.~~
    - [x] ~~Return action to RandomQuestionPresenter.Show(null) does not seem to work.~~
    - [x] ~~SetLanguage in Login without sourceAction seem to make the Login button not work anymore.~~
- [x] Doing return actions with URL parameters in MVC:
   - [x] Encoding return actions in URL’s instead of post data.
- [x] Index -> last page -> edit -> cancel -> Index
    - [x] Functional error: page index seems set to first page, not last.
- [x] Logout / Login:
    - [x] Exception: mvcUrl is null or empty.
- [x] Index -> details -> edit -> save
    - [x] Functional error: "question not found"
    - [x] It seems the id parameter is not used.
    - [x] It seems this is because it is not a URL parameter, but a URL path part, may require mapping the parameter explicitly in the ViewMappings.
- [x] Perhaps not all URL situations from MVC are accounted by a mapping between MVC and presenters. A different Url.Action might be needed that generates a URL that the framework might translate to a Presenter URL. But it seems a hack, because then the current URL in JavaScript might not be used as a ret URL for an action.
- [x] ~~Performance of translating MVC action info to presenter action info is probably not optimal since the introduction of nameless MVC parameters controller action parameters that are URL path parts rather than URL parameters.~~
- [x] ~~It may be dirty to abuse the ActionInfo objects to describe MVC actions instead of  actions, since the ActionInfo object has a PresenterName property, is then the ControllerName. It may be better to use MVC's own intrinsic ActionDescriptor for describing the MVC actions.~~
- [x] ~~URL parts might be explicitly mapped, that translate to parameters, rather than registering them as regular parameters.~~
- [x] ~~The default action might also be mapped so that the MVC action URLs work as ret URLs translated to Presenter action info.~~
- [x] ~~A more complete solution for taking into account all URL route options in the translation between the MVC layer and the Presenter layer might be: using all the routing rules set up with MVC. Perhaps you something might be used in MVC to translate from MVC URL’s to route values. Perhaps something internal to MVC, even. Perhaps unless a more complete solution would be built for that, situations that fail might be solved with hacks each time.~~
- [x] ~~Being more strict about parameter mapping? Making it required, not optional to map parameters, that are the same in both MVC and Presenter layer?~~

### 2018-05-20 Brainstorm Return Actions

- [x] The Demos.ReturnActions projects seem quite relevant. It might be relevant keeping the original ActionDispatcher-based ones. It may serve a purpose, for making a case for string-based ret variations. Just keeping all the variations. Keeping the deprecated framework code in a separate part of the demo projects.
- [x] For some reason Login in Demos.ReturnActions.NoViewModel does not seem to work anymore. It cannot find it.
- [x] Using QuestionAndAnswer project as a play ground.
- [x] ret parameter management
- [x] QuestionController does not seem to be finished regarding ret.
- [x] Each edit sub-action may need ret too,
- [x] Perhaps having ret in the view model might be easier for generating action links for edit sub-actions.
- [x] Then the view models of some sub-view models might change.
- [x] It might be wise to pass ret to the presenter layer and have it yield over those non-persisted properties.
- [x] I do not seem to remember, how we might have done it at my former employer. I remember it may have had more requirements and was quite a bit harder.
- [x] I may want to give it a rest now.
- [x] > My best bet seems to be:
- [x] Put return action info in the view model in a show method in the get action.
- [x] Perhaps make ret required. But this might be not nice for testing, but for this purpose a single slash as a dummy might do. This may prevent forgetting to supply the ret.
- [x] Testing and correcting it.
- [x] Create action seems to redirect to Edit/0, but upon reload, it seems to say "not found".
- [x] A double ret was seen in the Login upon QuestionCreate on QuestionIndex when not logged in. > Not reproducible.

### 2018-06-04 Brainstorm Return Actions

- [x] Working on ReturnActions demo with custom ActionDispatcher and no view mappings.
