### ISSUE TITLE
XML to object mapping / WCF-compatible soap client

### ISSUE THREAD

**Issue by jjvanzon** [jjvanzon/JJ.Framework#76]
Programmed around June 2014.

Because System.ServiceModel (WCF) at one point did not seem available on some mobile platforms, this was programmed:

- JJ.Framework.Xml.Linq: XML to object mapping, with features to support what WCF might expect.
- JJ.Framework.Soap: On top of that a soap client that may handle some of the infra structure, but might delegate message parsing and formatting to JJ.Framework.Xml.Linq.

Not all the possible features from the SOAP protocol or WCF might have been programmed.
Unity Game Engine did not always seem cooperative back then. It did not seem to support HttpWebRequest, which made for sort of complicating some choices, using a delegate to allow custom-handling of sending and receiving messages.

### Done

- [x] Building XML to send, not just parsing the received XML.
    - [x] ObjectToXmlConverter might be refined some more.

#### Collection handling

- [x] First did an IList<T> to which a List<T> would be assigned.
- [x] Then maybe ICollection.
- [x] Perhaps at first assume it might be IList<T>.
- [x] What if it is List<T>?
- [x] Trying out how arrays / collections look in the soap messages.
    - [x] They seemed singularized by using the class name.
- [x] Standard singularized name might be the class name.
    - [x] Perhaps also change that in JJ.Framework.Xml next to JJ.Framework.Xml.Linq.
    - [x] Also updated the summaries.
    - [x] Perhaps add a test to JJ.Framework.Xml.Linq.Tests.
- [x] A test with collections that might be send may be welcome.
- [x] JJ.Framework.Soap does not seem to handle arrays of simple types correctly yet. What may help with this is a separate namespace for array items of simple types and translation of specific primitives to different names. These differing names might not necessarily be the SOAP standard. It may what WCF wants.
- [x] Came up with a generic way to map item types to array element names.
- [x] Applied it non-generically in the WCF soap client.
- [x] Applied to sent message
- [x] Applied to received message.

#### Patterns

- [x] Using XElement instead of XContainer and getting the root XElement of an XDocument.
- [x] Applying same pattern to XML attributes as done for converting elements.
- [x] And also to XML arrays.
- [x] The overloads with less parameters / less dependency on parents.
- [x] ~~There may be feature-ifs, which might replaced by specialization through inheritance and a factory.~~ > It really does not seem that bad.
- [x] When implementing what's needed now, it may become a rather inconsistent API. > JJ.Framework.Xml having less features is ok perhaps.
- [x] Using GetGetMethod might make it more platform safe.

#### Namespace handing

- [x] Made XmlToObjectConverter namespace-independent (but not necessarily fast) for now.
- [x] The namespace-independent way of getting elements might not be fast.
- [x] > Not sure the ‘normal’ way of getting nodes is faster, but could try supporting namespace mappings.
- [x] (.NET namespace string -> XML namespace string)
- [x] For ObjectToXmlConverter namespaces might be an issue.
- [x] Explicit control over namespace prefixes might be a problem.
- [x] ~~Maybe let ObjectToXmlConverter gather up namespaces and return them.~~ > Instead just generating them in a standard way. If someone needs different ones, they may have to convert them themselves.
XmlNs’s may be added to the root / an element of the XElement structure. Perhaps not leave that up to the caller of ObjectToXmlConverter. ObjectToXmlConverter might do that automatically. This might solve the problem of explicitly passing namespaces and namespace mappings to the ObjectToXmlConverter. However, transforming the dotNetNamespace to the xmlNamespace might not be solved then yet. It might be an option, to set the full namespace name to just the .NET namespace and later transforming those XNamespaces. And in that transformation it may be determined what the prefixes and xmlns’s might be and then ‘number’ those ("a", "b", "c", etc.) and keeping a few reserved ones for the soap and operation XML namespaces (perhaps simply "a" and "b"). First maybe check if it is possible to just alter the XNamespace object and have identity integrity in tact (all the elements’ XNamespace might change when you change the XNamespace).
- [x] Documenting that namespaces may be ignored when parsing the end result.
- [x] Operation namespace might not have to be http://tempuri.org/ even for WCF. A solution might be to use namespace mappings.
But then they may need to be applied to the whole soap message, instead of just the parameter elements.
In that case would it work to default to the default namespace, if a namespace mapping is not supplied?

#### Name handling

- [x] Default behavior seems to be to map property names to camel case versions for the XML node names.
- [x] Supporting the property names as literally present in the XML and not only their camel case versions.
- [x] The summaries of the XmlToObjectConverter might be adapted to that expected casing and that it can be overridden.
- [x] Refactoring name resolution. Making all name generation part of the NamespaceResolver but perhaps call it something else. NameManager or something.
- [x] Integrating the NamespaceResolver code into the NameManager. 
- [x] Refactor ingthe NameManager some more.

#### Null handling

- [x] Managing nullability a bit better. Trying to providing clearer rules on it. Explained the reasons for those rules in the class and member summaries.
- [x] JJ.Framework.Soap did not seem to handle null correctly (‘i:nil’)
- [x] Generating nil-elements
- [x] Generating nil XML namespace
- [x] Parsing standard XML formatting in the received message might be improved.
- [x] Nils seem to be sent, but received nils might not be parsed.
- [x] > Null is may still not be handled optimally, because it seems to only checks it for child elements from parent elements, not elements in an xml array necessarily.

#### Transport handling

- [x] Later it might be taken a bit further, perhaps making WcfSoapClient expose a Channel with the specified interface. Extra work, but it might prevent using strings and be weak typing. It might be a bit difficult to do it the way WCF does it, because that might require dynamically compiled classes. It might be done with lambda expressions, so no dynamically compiled classes, just use the method info and its parameter infos.
- [x] Eventually may refactor out the non-generic WcfSoapClient, maybe. > Turned it into an internal class.
- [x] Parameters might not have worked, when they are not composite types.

#### Value formatting

- [x] It appears there could be multiple value formats for XML. See the option parameters of the System.Xml.XmlConvert methods.
- [x] > Handled with a disclaimer in some comment in the code.

#### Alphabetical element order

- [x] WCF seems to like it, when the properties of composite types are alphabetically ordered.

#### Testing

- [x] Some tests of JJ.Framework.Xml.Linq might still have failed.
- [x] Extending the test Test_WcfSoapClient_SendAndGetComplicatedObject: returning actual data instead of a object filled with default values.

### TODO

- [ ] Already 75 hours put into the soap client and XML API.
- [ ] Always formatting char as an int, might not be standard. It may only work for WCF.
- [ ] Resolving nullable type names for XML array elements.
- [ ] JJ.Framework.Xml(.Linq) may fail when a collection item is null for converters both ways.
- [ ] JJ.Framework.Soap: byte arrays might be handled in a special way.
- [ ] Soap clients may need an Invoke variation, that would return void.
- [ ] Not sure how good the support of System.Xml.XmlConvert is on mobile platforms. Windows Phone 8 seems to have it, though.
- [ ] Cleaning up test service: removing unused methods?

### Postponed

- [ ] ~ Namespace ignoring may be faster when removing the namespaces first and then parsing.
- [ ] ~ ObjectToXmlConverter may be helped by more info in the summaries.
- [ ] ~ Perhaps making the summaries mention, how the XML node’s name may be determined, and perhaps other calls to helpers too.
- [ ] ~ Not all the SOAP rules might be followed.
    - [x] http://www.intertwingly.net/stories/2002/03/16/aGentleIntroductionToSoap.html
    - [x] http://www.intertwingly.net/stories/2002/01/25/whatObjectDoesSoapAccess.html
    - [x] http://www.soapware.org/bdg/ 
    - [ ] ~ > It may not be breaking any rules, but also not everything might be supported. Perhaps not supported: specifying the encoding. Explicit specification of data types, xsi:null and standard soap arrays.
    - [ ] ~ http://msdn.microsoft.com/en-us/library/ff690589%28v=sql.105%29.aspx 
- [ ] ~ JJ.Framework.Xml.Linq: Custom collection types might not be supported.
- [ ] ~ JJ.Framework.Xml may not have as many features as JJ.Framework.Xml.Linq.
- [ ] ~ ObjectToXmlConverter might be made better portable from System.Xml.Linq to System.Xml.
- [ ] ~ JJ.Framework.Xml.Linq: May values be formatted correctly according to the SOAP protocol. What might be done about culture? Might just using en-US be correct? Might custom date formatting be desired?
- [ ] ~ JJ.Framework.Xml.Linq: Might standard value formatting of System.Xml.Linq be ok? > Maybe not always. For soap, maybe, for config files, en-US might be desired. Some projects do not use JJ.Framework.Xml.Linq for config files, but JJ.Framework.Xml instead.
